In [42]:
import pandas as pd
import numpy as np

In [43]:
# giving the column names to the datset

columns=[
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income"
]

In [44]:
# adult.data dataset in the train_df

train_df=pd.read_csv(
    "C:\\Users\\vaish\\OneDrive\\Documents\\Adult_Income_Data_Cleaning_and_EDA\\data\\adult.data",
    names=columns,
    sep=",",
    skipinitialspace=True
)

train_df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [45]:
print(train_df.shape)

(32561, 15)

In [46]:
# adult.test dataset in the test_df

test_df=pd.read_csv(
    "C:\\Users\\vaish\\OneDrive\\Documents\\Adult_Income_Data_Cleaning_and_EDA\\data\\adult.test",
    names=columns,
    sep=",",
    skipinitialspace=True,
    skiprows=1
)

test_df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.

In [47]:
# # converting the tarin_df and test_df into train and test

# train_df["source_split"]="train"
# test_df["source_split"]="test"
# df

In [48]:
# now concat both of them

df=pd.concat(
    [train_df,test_df],
    ignore_index=True
)

In [49]:
print(df.shape)

(48842, 15)

In [50]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [51]:
df.shape

(48842, 15)

In [52]:
df.dtypes

age               int64
workclass           str
fnlwgt            int64
education           str
education_num     int64
marital_status      str
occupation          str
relationship        str
race                str
sex                 str
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country      str
income              str
dtype: object

In [53]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [54]:
# Removing the leading and trailing spaces from all the catogrical columns

columns_cat=df.select_dtypes(include="object").columns

for col in columns_cat:
    df[col]=df[col].str.strip()

C:\Users\vaish\AppData\Local\Temp\ipykernel_5296\2682539964.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columns_cat=df.select_dtypes(include="object").columns

In [55]:
# contains ? in place of the unknown values

df=df.replace("?",np.nan)

In [56]:
df.isnull().sum()

age                  0
workclass         2799
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     857
income               0
dtype: int64

In [57]:
missing_values=pd.DataFrame(
    {
        "Missing_Count": df.isnull().sum(),
        "Missing_Percentage":df.isnull().mean()*100
    }
)
missing_values=missing_values[missing_values["Missing_Count"]>0]

print(missing_values)

                Missing_Count  Missing_Percentage
workclass                2799            5.730724
occupation               2809            5.751198
native_country            857            1.754637

In [58]:
# filling the missing values with unknown
missing_cat=[
    "workclass",
    "occupation",
    "native_country"
]

for i in missing_cat:
    df[i]=df[i].fillna("Unknown")

df[missing_cat].isnull().sum()

workclass         0
occupation        0
native_country    0
dtype: int64

In [59]:
# income Column

df["income"]=df["income"].replace(".","",regex=False)

In [60]:
# filtering out the higher income than 50k

df["high_income"]=(df["income"]==">50K").astype(int)

df[["income", "high_income"]].head(10)

  income  high_income
0  <=50K            0
1  <=50K            0
2  <=50K            0
3  <=50K            0
4  <=50K            0
5  <=50K            0
6  <=50K            0
7   >50K            1
8   >50K            1
9   >50K            1

In [61]:
# numerical columns

numeric_col=[
    "age",
    "fnlwgt",
    "education_num",
    "capital_gain",
    "capital_loss",
    "hours_per_week"
]

for i in numeric_col:
    df[i]=pd.to_numeric(df[i],errors="coerce")

df[numeric_col].dtypes
df[numeric_col].isnull().sum()
df[numeric_col].duplicated().sum()

np.int64(481)

In [62]:
# creating the different age groups

df["age_group"]=pd.cut(df["age"],
                       bins=[1,25,35,45,55,65,100],
                       labels=["18-25",'26-35','36-45','46-55','56-65','66+'])

df['age_group'].value_counts()

age_group
26-35    12719
36-45    11952
18-25     9627
46-55     8296
56-65     4445
66+       1803
Name: count, dtype: int64

In [63]:
# creating the different working hour groups

df["hour_group"]=pd.cut(df["hours_per_week"],
                        bins=[0,20,40,60,150],
                        labels=['0-20','21-40','41-60','61+']
)


df["hour_group"].value_counts()

hour_group
21-40    30037
41-60    12676
0-20      4453
61+       1676
Name: count, dtype: int64

In [64]:
# creating the net capital column from capital gain and captial loss

df["net_capital"]=(df["capital_gain"]-df["capital_loss"])

df[["capital_gain","capital_loss","net_capital"]].head()

   capital_gain  capital_loss  net_capital
0          2174             0         2174
1             0             0            0
2             0             0            0
3             0             0            0
4             0             0            0

In [65]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
high_income       0
age_group         0
hour_group        0
net_capital       0
dtype: int64

In [66]:
# final inspection of the dataset

print("Shape: ",df.shape)

print("Columns: ",df.columns)

print("Data Types: ",df.dtypes)

print("Duplicated: ",df.duplicated().sum())

Shape:  (48842, 19)
Columns:  Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income', 'high_income', 'age_group', 'hour_group', 'net_capital'],
      dtype='str')
Data Types:  age                  int64
workclass              str
fnlwgt               int64
education              str
education_num        int64
marital_status         str
occupation             str
relationship           str
race                   str
sex                    str
capital_gain         int64
capital_loss         int64
hours_per_week       int64
native_country         str
income                 str
high_income          int64
age_group         category
hour_group        category
net_capital          int64
dtype: object
Duplicated:  29

In [67]:
df.columns=df.columns.str.strip().str.title()

In [68]:
df["Workclass"].unique()
df["Education"].unique()
df["Marital_Status"].unique()
df["Occupation"].unique()
df["Relationship"].unique()
df["Race"].unique()
df["Sex"].unique()
df["Native_Country"].unique()

<StringArray>
[             'United-States',                       'Cuba',
                    'Jamaica',                      'India',
                    'Unknown',                     'Mexico',
                      'South',                'Puerto-Rico',
                   'Honduras',                    'England',
                     'Canada',                    'Germany',
                       'Iran',                'Philippines',
                      'Italy',                     'Poland',
                   'Columbia',                   'Cambodia',
                   'Thailand',                    'Ecuador',
                       'Laos',                     'Taiwan',
                      'Haiti',                   'Portugal',
         'Dominican-Republic',                'El-Salvador',
                     'France',                  'Guatemala',
                      'China',                      'Japan',
                 'Yugoslavia',                       'Peru',
 'Outlying-US(Guam-USVI-etc)',                   'Scotland',
            'Trinadad&Tobago',                     'Greece',
                  'Nicaragua',                    'Vietnam',
                       'Hong',                    'Ireland',
                    'Hungary',         'Holand-Netherlands']
Length: 42, dtype: str

In [69]:
df

,Age,Workclass,Fnlwgt,Education,Education_Num,Marital_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_Per_Week,Native_Country,Income,High_Income,Age_Group,Hour_Group,Net_Capital
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,0,36-45,21-40,2174
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0,46-55,0-20,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0,36-45,21-40,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0,46-55,21-40,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0,26-35,21-40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.,0,36-45,21-40,0
48838,64,Unknown,321403,HS-grad,9,Widowed,Unknown,Other-relative,Black,Male,0,0,40,United-States,<=50K.,0,56-65,21-40,0
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.,0,36-45,41-60,0
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.,0,36-45,21-40,5455
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.,0,26-35,41-60,0

In [70]:
df.to_csv("adult_income.csv",index=False)